package com.websitestudios.validator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.util.Set;
import java.util.List;

/**
 * Validates email domains against a blocklist of disposable/temporary email
 * providers.
 *
 * This is NOT a JSR-303 annotation validator — it's a service-level validator
 * called explicitly in the service layer for flexibility.
 *
 * Usage in service:
 * if (!emailDomainValidator.isValidDomain(email)) {
 * throw new InvalidInputException("email", "Disposable email addresses are not
 * allowed");
 * }
 */
@Component
public class EmailDomainValidator {

    private static final Logger log = LoggerFactory.getLogger(EmailDomainValidator.class);

    /**
     * Blocklist of known disposable/temporary email domains.
     * This is a curated subset — extend as needed.
     *
     * In production, consider loading from a database or external API
     * for a more comprehensive list.
     */
    private static final Set<String> BLOCKED_DOMAINS = Set.copyOf(List.of(
            // Popular disposable email services
            // ════════════════════════════════════════════════════════════
            // TIER 1: Most Popular Disposable Email Services
            // ════════════════════════════════════════════════════════════
            "mailinator.com",
            "guerrillamail.com",
            "guerrillamail.net",
            "guerrillamail.org",
            "guerrillamail.de",
            "guerrillamail.biz",
            "guerrillamailblock.com",
            "tempmail.com",
            "temp-mail.org",
            "temp-mail.io",
            "temp-mail.de",
            "throwaway.email",
            "10minutemail.com",
            "10minutemail.net",
            "10minutemail.org",
            "10minutemail.co.za",
            "yopmail.com",
            "yopmail.fr",
            "yopmail.net",
            "yopmail.gq",
            "trashmail.com",
            "trashmail.net",
            "trashmail.org",
            "trashmail.me",
            "trashmail.io",
            "trashmail.at",

            // ════════════════════════════════════════════════════════════
            // TIER 2: Well-Known Disposable Services
            // ════════════════════════════════════════════════════════════
            "sharklasers.com",
            "grr.la",
            "guerrillamail.info",
            "dispostable.com",
            "maildrop.cc",
            "mailnesia.com",
            "mintemail.com",
            "tempail.com",
            "mohmal.com",
            "mohmal.im",
            "mohmal.in",
            "mohmal.tech",
            "burpcollaborator.net",
            "mailcatch.com",
            "nada.email",
            "nada.ltd",
            "getnada.com",
            "tempmailo.com",
            "emailondeck.com",
            "33mail.com",
            "discard.email",
            "fakeinbox.com",
            "mailsac.com",
            "harakirimail.com",
            "mailexpire.com",
            "tempinbox.com",

            // ════════════════════════════════════════════════════════════
            // TIER 3: Additional Popular Disposable Providers
            // ════════════════════════════════════════════════════════════
            "mailtemp.net",
            "mailtemp.org",
            "tempr.email",
            "tempmail.ninja",
            "tempmail.plus",
            "tempmail.dev",
            "tempmail.us",
            "tempmail.lol",
            "tempmailer.com",
            "tempmailer.de",
            "tmpmail.net",
            "tmpmail.org",
            "tempmailaddress.com",
            "tempmails.net",
            "tempmails.org",
            "emailfake.com",
            "fakemailgenerator.com",
            "generator.email",
            "inboxkitten.com",
            "mailgw.com",
            "crazymailing.com",
            "disposableemailaddresses.emailmiser.com",
            "guerrillamail.xyz",
            "mailforspam.com",
            "spam4.me",
            "spambox.us",
            "spamfree24.org",
            "spamgourmet.com",
            "spamgourmet.net",
            "spamgourmet.org",
            "spamspot.com",
            "spamtrail.com",

            // ════════════════════════════════════════════════════════════
            // TIER 4: Throwaway / One-Time Use Domains
            // ════════════════════════════════════════════════════════════
            "throaway.com",
            "throwam.com",
            "throwawayemailaddress.com",
            "tmail.ws",
            "tmails.net",
            "tmpbox.net",
            "tmpmail.co",
            "uggsrock.com",
            "veryrealemail.com",
            "wetrainbayarea.com",
            "wetrainbayarea.org",
            "wh4f.org",
            "whyspam.me",
            "wilemail.com",
            "willhackforfood.biz",
            "wimsg.com",
            "wronghead.com",
            "wuzup.net",
            "wuzupmail.net",
            "wwwnew.eu",
            "xagloo.com",
            "xemaps.com",
            "xents.com",
            "xjoi.com",
            "xoxy.net",

            // ════════════════════════════════════════════════════════════
            // TIER 5: Trash / Junk Mail Services
            // ════════════════════════════════════════════════════════════
            "jetable.com",
            "jetable.fr.nf",
            "jetable.net",
            "jetable.org",
            "jourrapide.com",
            "junkmail.ga",
            "junkmail.gq",
            "klassmaster.com",
            "klzlk.com",
            "koszmail.pl",
            "kurzepost.de",
            "lackmail.net",
            "lavabit.com",
            "letthemeatspam.com",
            "lhsdv.com",
            "lifebyfood.com",
            "link2mail.net",
            "litedrop.com",
            "lol.ovpn.to",
            "lolfreak.net",
            "lookugly.com",
            "lopl.co.cc",
            "lortemail.dk",
            "lovemeleaveme.com",
            "lr78.com",
            "m4ilweb.info",
            "maboard.com",
            "mail-temporaire.fr",
            "mail.by",
            "mail.mezimages.net",
            "mail2rss.org",
            "mail333.com",
            "mail4trash.com",

            // ════════════════════════════════════════════════════════════
            // TIER 6: Anonymous / Privacy Email Services (Disposable)
            // ════════════════════════════════════════════════════════════
            "anonymbox.com",
            "antichef.com",
            "antichef.net",
            "antireg.ru",
            "antispam.de",
            "antispammail.de",
            "armyspy.com",
            "artman-conception.com",
            "azmeil.tk",
            "baxomale.ht.cx",
            "beefmilk.com",
            "bigstring.com",
            "bincimail.com",
            "bio-muesli.net",
            "bladesmail.net",
            "bloatbox.com",
            "bobmail.info",
            "bodhi.lawlita.com",
            "bofthew.com",
            "bootybay.de",
            "boun.cr",
            "bouncr.com",
            "breakthru.com",
            "brefmail.com",
            "brennendesreich.de",
            "broadbandninja.com",
            "bsnow.net",
            "buffemail.com",
            "bugmenot.com",
            "bumpymail.com",
            "bund.us",
            "bundes-ede.de",
            "burnthespam.info",
            "burstmail.info",
            "buymoreplays.com",
            "buyusedlibrarybooks.org",
            "byom.de",

            // ════════════════════════════════════════════════════════════
            // TIER 7: Catch-All / Wildcard Disposable Domains
            // ════════════════════════════════════════════════════════════
            "cachedot.net",
            "casualdx.com",
            "centermail.com",
            "centermail.net",
            "chammy.info",
            "cheatmail.de",
            "chogmail.com",
            "choicemail1.com",
            "clixser.com",
            "clrmail.com",
            "cmail.club",
            "cmail.com",
            "cmail.net",
            "cmail.org",
            "coldemail.info",
            "cool.fr.nf",
            "correo.blogos.net",
            "cosmorph.com",
            "courriel.fr.nf",
            "courrieltemporaire.com",
            "crapmail.org",
            "crazespaces.pw",
            "crazymailing.com",
            "cubiclink.com",
            "curryworld.de",
            "cust.in",
            "cuvox.de",
            "dacoolest.com",
            "dandikmail.com",
            "dayrep.com",
            "dbunker.com",
            "dcemail.com",
            "deadaddress.com",
            "deadchildren.org",
            "deadfake.cf",
            "deadfake.ga",
            "deadfake.ml",
            "deadfake.tk",
            "deadspam.com",
            "deagot.com",
            "dealja.com",
            "despam.it",
            "despammed.com",
            "devnullmail.com",

            // ════════════════════════════════════════════════════════════
            // TIER 8: International Disposable Email Providers
            // ════════════════════════════════════════════════════════════
            "dingbone.com",
            "disbox.net",
            "disbox.org",
            "discardmail.com",
            "discardmail.de",
            "disposable.cf",
            "disposable.ga",
            "disposable.ml",
            "disposable-email.ml",
            "disposableaddress.com",
            "disposableemailaddresses.emailmiser.com",
            "disposableinbox.com",
            "dispose.it",
            "disposeamail.com",
            "disposemail.com",
            "dispomail.eu",
            "dodgeit.com",
            "dodgit.com",
            "dodgit.org",
            "dodsi.com",
            "doiea.com",
            "domforfb1.tk",
            "domforfb2.tk",
            "domforfb3.tk",
            "domforfb4.tk",
            "domforfb5.tk",
            "domforfb6.tk",
            "domforfb7.tk",
            "domforfb8.tk",
            "domozmail.com",
            "donemail.ru",
            "dontreg.com",
            "dontsendmespam.de",
            "dotmsg.com",
            "drdrb.com",
            "drdrb.net",
            "droplar.com",
            "dropmail.me",
            "duam.net",
            "dudmail.com",
            "dump-email.info",
            "dumpandjunk.com",
            "dumpmail.de",
            "dumpyemail.com",
            "duskmail.com",
            "e4ward.com",

            // ════════════════════════════════════════════════════════════
            // TIER 9: Inbox / Receiving Only Services
            // ════════════════════════════════════════════════════════════
            "easytrashmail.com",
            "edv.to",
            "einmalmail.de",
            "einrot.com",
            "einrot.de",
            "eintagsmail.de",
            "email-fake.cf",
            "email-fake.com",
            "email-fake.ga",
            "email-fake.gq",
            "email-fake.ml",
            "email-fake.tk",
            "email60.com",
            "emailage.cf",
            "emailage.ga",
            "emailage.gq",
            "emailage.ml",
            "emailage.tk",
            "emaildienst.de",
            "emailgo.de",
            "emailias.com",
            "emailigo.de",
            "emailinfive.com",
            "emaillime.com",
            "emailmiser.com",
            "emailproxsy.com",
            "emails.ga",
            "emailsensei.com",
            "emailspam.cf",
            "emailspam.ga",
            "emailspam.gq",
            "emailspam.ml",
            "emailspam.tk",
            "emailtemporanea.com",
            "emailtemporanea.net",
            "emailtemporar.ro",
            "emailtemporario.com.br",
            "emailthe.net",
            "emailtmp.com",
            "emailto.de",
            "emailwarden.com",
            "emailx.at.hm",
            "emailxfer.com",
            "emailz.cf",
            "emailz.ga",
            "emailz.gq",
            "emailz.ml",
            "emz.net",

            // ════════════════════════════════════════════════════════════
            // TIER 10: Modern / Recent Disposable Services
            // ════════════════════════════════════════════════════════════
            "enayu.com",
            "enterto.com",
            "ephemail.net",
            "ero-tube.org",
            "etranquil.com",
            "etranquil.net",
            "etranquil.org",
            "evopo.com",
            "explodemail.com",
            "express.net.ua",
            "eyepaste.com",
            "fakedemail.com",
            "fakemail.fr",
            "fakemailz.com",
            "fammix.com",
            "fansworldwide.de",
            "fantasymail.de",
            "fastacura.com",
            "fastchevy.com",
            "fastchrysler.com",
            "fastkawasaki.com",
            "fastmazda.com",
            "fastmitsubishi.com",
            "fastnissan.com",
            "fastsubaru.com",
            "fastsuzuki.com",
            "fasttoyota.com",
            "fastyamaha.com",
            "fatflap.com",
            "fdfdsfds.com",
            "fightallspam.com",
            "filzmail.com",
            "fixmail.tk",
            "fizmail.com",
            "fleckens.hu",
            "flurred.com",
            "flurred.ru",
            "flyspam.com",
            "footard.com",
            "forgetmail.com",
            "fr33mail.info",
            "frapmail.com",
            "freemails.cf",
            "freemails.ga",
            "freemails.ml",
            "freundin.ru",
            "friendlymail.co.uk",
            "front14.org",
            "fuckingduh.com",
            "fudgerub.com",
            "fux0ringduh.com",

            // ════════════════════════════════════════════════════════════
            // TIER 11: API-Based Disposable Email Services
            // ════════════════════════════════════════════════════════════
            "garliclife.com",
            "gehensiull.com",
            "gelitik.in",
            "get-mail.cf",
            "get-mail.ga",
            "get-mail.ml",
            "get-mail.tk",
            "get1mail.com",
            "get2mail.fr",
            "getairmail.cf",
            "getairmail.com",
            "getairmail.ga",
            "getairmail.gq",
            "getairmail.ml",
            "getairmail.tk",
            "getmails.eu",
            "getonemail.com",
            "getonemail.net",
            "ghosttexter.de",
            "giantmail.de",
            "girlsundertheinfluence.com",
            "gishpuppy.com",
            "gmial.com",
            "goemailgo.com",
            "gorillaswithdirtyarmpits.com",
            "gotmail.com",
            "gotmail.net",
            "gotmail.org",
            "gotti.otherinbox.com",
            "gowikibooks.com",
            "gowikicampus.com",
            "gowikicars.com",
            "gowikifilms.com",
            "gowikigames.com",
            "gowikimusic.com",
            "gowikinetwork.com",
            "gowikitravel.com",
            "gowikitv.com",
            "grandmamail.com",
            "grandmasmail.com",
            "great-host.in",
            "greensloth.com",
            "greyspacem.com",

            // ════════════════════════════════════════════════════════════
            // TIER 12: Hacker / Security Testing Disposable Emails
            // ════════════════════════════════════════════════════════════
            "gsrv.co.uk",
            "guerillamail.biz",
            "guerillamail.com",
            "guerillamail.de",
            "guerillamail.info",
            "guerillamail.net",
            "guerillamail.org",
            "gustr.com",
            "h8s.org",
            "hacccc.com",
            "haltospam.com",
            "hatespam.org",
            "herp.in",
            "hidemail.de",
            "hidzz.com",
            "hmamail.com",
            "hopemail.biz",
            "hotpop.com",
            "hulapla.de",
            "hushmail.me",
            "ichimail.com",
            "ieh-mail.de",
            "igirl.com",
            "ihateyoualot.info",
            "iheartspam.org",
            "ikbenull.nl",
            "imails.info",
            "inbax.tk",
            "inbox.si",
            "inboxalias.com",
            "inboxbear.com",
            "inboxclean.com",
            "inboxclean.org",
            "inboxproxy.com",
            "incognitomail.com",
            "incognitomail.net",
            "incognitomail.org",
            "ineec.net",
            "infocom.zp.ua",
            "instant-mail.de",
            "instantemailaddress.com",
            "ip6.li",
            "ipoo.org",
            "irish2me.com",
            "iwi.net",

            // ════════════════════════════════════════════════════════════
            // TIER 13: Short-Lived / Auto-Expiring Email Domains
            // ════════════════════════════════════════════════════════════
            "jetable.pp.ua",
            "jnxjn.com",
            "jobbikszansen.hu",
            "joooid.com",
            "jsrsolutions.com",
            "junk1e.com",
            "junkmail.com",
            "junkmail.ga",
            "junkmail.gq",
            "kasmail.com",
            "kaspop.com",
            "keepmymail.com",
            "killmail.com",
            "killmail.net",
            "kimsdisk.com",
            "kingsq.ga",
            "kiois.com",
            "kir.ch.tc",
            "klassmaster.net",
            "klzlk.com",
            "kook.ml",
            "koszmail.pl",
            "kulturbetrieb.info",
            "kurzepost.de",
            "l33r.eu",
            "labetteravede.com",
            "lackmail.net",
            "lackmail.ru",
            "landmail.co",
            "lastmail.co",
            "lastmail.com",
            "lazyinbox.com",
            "lazyinbox.us",
            "letthemeatspam.com",
            "lhsdv.com",
            "libox.fr",
            "lifebyfood.com",
            "link2mail.net",
            "litedrop.com",
            "loadby.us",
            "login-email.cf",
            "login-email.ga",
            "login-email.ml",
            "login-email.tk",
            "logular.com",
            "lol.ovpn.to",
            "lolfreak.net",
            "lookugly.com",

            // ════════════════════════════════════════════════════════════
            // TIER 14: Mailinator Variants & Subdomains
            // ════════════════════════════════════════════════════════════
            "mailinator.net",
            "mailinator.org",
            "mailinator.us",
            "mailinator2.com",
            "mailinator2.net",
            "mailinater.com",
            "mailincubator.com",
            "mailismagic.com",
            "mailmate.com",
            "mailme.ir",
            "mailme.lv",
            "mailme24.com",
            "mailmetrash.com",
            "mailmoat.com",
            "mailms.com",
            "mailnator.com",
            "mailnull.com",
            "mailorg.org",
            "mailpick.biz",
            "mailproxsy.com",
            "mailquack.com",
            "mailrock.biz",
            "mailscrap.com",
            "mailshell.com",
            "mailsiphon.com",
            "mailslapping.com",
            "mailslite.com",
            "mailtemp.info",
            "mailtome.de",
            "mailtothis.com",
            "mailtrash.net",
            "mailtv.net",
            "mailtv.tv",
            "mailzilla.com",
            "mailzilla.org",
            "mailzilla.orgmbx.cc",
            "makemetheking.com",

            // ════════════════════════════════════════════════════════════
            // TIER 15: Miscellaneous Global Disposable Domains
            // ════════════════════════════════════════════════════════════
            "manifestgenerator.com",
            "manybrain.com",
            "mbx.cc",
            "mega.zik.dj",
            "meinspamschutz.de",
            "meltmail.com",
            "messagebeamer.de",
            "mezimages.net",
            "mfsa.ru",
            "mierdamail.com",
            "migmail.pl",
            "migumail.com",
            "ministry-of-silly-walks.de",
            "mintemail.com",
            "misterpinball.de",
            "mmmmail.com",
            "moakt.com",
            "moakt.co",
            "moakt.ws",
            "mobileninja.co.uk",
            "mohmal.com",
            "moncourrier.fr.nf",
            "monemail.fr.nf",
            "monmail.fr.nf",
            "monumentmail.com",
            "msa.minsmail.com",
            "mt2015.com",
            "mt2016.com",
            "mx0.wwwnew.eu",
            "my10minutemail.com",
            "myalias.pw",
            "mycard.net.ua",
            "mycleaninbox.net",
            "myemailboxy.com",
            "mymail-in.net",
            "mymailoasis.com",
            "mynetstore.de",
            "mypacks.net",
            "mypartyclip.de",
            "myphantom.com",
            "mysamp.de",
            "myspaceinc.com",
            "myspaceinc.net",
            "myspaceinc.org",
            "myspacepimpedup.com",
            "mytemp.email",
            "mytempemail.com",
            "mytempmail.com",
            "mytrashmail.com",
            "nabala.com",
            "neomailbox.com",
            "nepwk.com",
            "nervmich.net",
            "nervtansen.de",
            "netmails.com",
            "netmails.net",
            "neverbox.com",
            "nevermail.de",
            "nexttrend.com",
            "nfast.net",
            "nguyenusedcars.com",
            "nhmail.com",
            "nmail.cf",
            "nnh.com",
            "nnot.net",
            "noblepioneer.com",
            "nobulk.com",
            "noclickemail.com",
            "nogmailspam.info",
            "nomail.pw",
            "nomail.xl.cx",
            "nomail2me.com",
            "nomorespamemails.com",
            "nonspam.eu",
            "nonspammer.de",
            "noref.in",
            "nospam.ze.tc",
            "nospam4.us",
            "nospamfor.us",
            "nospammail.net",
            "nospamthanks.info",
            "nothingtoseehere.ca",
            "notmailinator.com",
            "notsomuch.com",
            "nowhere.org",
            "nowmymail.com",
            "nurfuerspam.de",
            "nus.edu.sg"));

    /**
     * Check if the email's domain is allowed (not in blocklist).
     *
     * @param email Full email address
     * @return true if domain is allowed, false if blocked
     */
    public boolean isValidDomain(String email) {
        if (email == null || !email.contains("@")) {
            return false;
        }

        String domain = email.substring(email.lastIndexOf("@") + 1).toLowerCase().trim();

        if (BLOCKED_DOMAINS.contains(domain)) {
            log.warn("Blocked disposable email domain detected: {}", domain);
            return false;
        }

        return true;
    }

    /**
     * Get the domain part of an email.
     */
    public String extractDomain(String email) {
        if (email == null || !email.contains("@")) {
            return null;
        }
        return email.substring(email.lastIndexOf("@") + 1).toLowerCase().trim();
    }
}